# This workflow requires a personal access token for uirouterbot
name: Weekly Dependency Bumps
on:
  schedule:
    - cron: '52 03 * * 5'

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-latest
    name: Upgrade dependencies
    strategy:
      matrix:
        deptype: ['devDependencies']
        latest: [true, false]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.password ${{ secrets.UIROUTERBOT_PAT }}
          git remote set-url origin $(git remote get-url origin | sed -e 's/ui-router/uirouterbot/')
          git fetch --unshallow -p origin
      - name: Upgrade dependencies
        id: upgrade
        uses: ui-router/publish-scripts/actions/upgrade@actions-upgrade-v1.0.0
        with:
          exclude: 'typescript'
          deptype: ${{ matrix.deptype }}
          latest: ${{ matrix.latest }}
      - name: Create Pull Request
        if: ${{ steps.upgrade.outputs.upgrades != '' }}
        # the following hash is from https://github.com/peter-evans/create-pull-request/releases/tag/v2.7.0
        uses: peter-evans/create-pull-request@340e629d2f63059fb3e3f15437e92cfbc7acd85b
        with:          
          token: ${{ secrets.UIROUTERBOT_PAT }}
          request-on-parent: true
          branch-suffix: 'random'
          commit-message: 'chore(package): Update ${{ steps.upgrade.outputs.upgrade-count }} ${{ matrix.deptype }} to ${{ steps.upgrade.outputs.upgrade-strategy }}: ${{ steps.upgrade.outputs.upgrades }}'
          title: 'chore(package): Weekly ${{ matrix.deptype }} bump (latest: ${{ matrix.latest }})'
          body: |
            Update ${{ steps.upgrade.outputs.upgrade-count }} ${{ matrix.deptype }} to ${{ steps.upgrade.outputs.upgrade-strategy }}

            ${{ steps.upgrade.outputs.upgrades }}

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
